destination: ./_site
auto: false
lsi: false
server_port: 4000
pygments: true
markdown: rdiscount
permalink: date
include: _dynamic
exclude: readme.md test.idx
cobbler:
    version: 2.2.3-1
    released: 2012-06-07
    versions: [2.2.3-1]
