title: Cobbler
description: Officaial website for the Cobbler-Project.
url: "https://cobbler.github.io"
lsi: false
highlighter: rouge
markdown: rdiscount
permalink: "/blog/:year/:month/:day/:title.html"
paginate: 5
paginate_path: "/blog/:num/"
exclude: ['README.md', 'Dockerfile', 'Gemfile', 'Gemfile.lock', 'dockerfiles', '_site', '.idea']
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
cobbler:
  version: 2.8.4
  released: 2018-11-23
  versions: [2.8.4]
