title: Cobbler
description: Officaial website for the Cobbler-Project.
url: "https://cobbler.github.io"
lsi: false
highlighter: rouge
markdown: rdiscount
permalink: date
exclude: ['README.md', 'Dockerfile', 'Gemfile', 'Gemfile.lock', 'dockerfiles']
plugins:
  - jekyll-paginate
cobbler:
  version: 2.8.4
  released: 2018-11-23
  versions: [2.8.4]
