destination: ./_site
auto: true
lsi: true
server_port: 4000
pygments: true
markdown: rdiscount
permalink: date
exclude: readme.md
cobbler:
    version: 2.2.3-1
    released: 2012-06-07
    versions: [2.2.3-1]
